export type Phrase = {
  id: string;
  textWithError: string;
  wrongWord: string;
  correctWord: string;
  alternatives: string[];
  explanation: string;
  itemCorrect?: string;
};

export const SAMPLE_PHRASES: Phrase[] = [
  {
    id: 'p1',
    textWithError: 'Antes de dormir, João sempre rega os dentes para evitar cáries.',
    wrongWord: 'rega',
    correctWord: 'escova',
    alternatives: ['escova', 'planta', 'molha'],
    explanation: 'Rega-se plantas; dentes se escovam.',
    itemCorrect: 'Dentes',
  },
  {
    id: 'p2',
    textWithError: 'No verão, é comum as crianças congelarem no parque até tarde.',
    wrongWord: 'congelarem',
    correctWord: 'brincarem',
    alternatives: ['brincarem', 'esfriarem', 'endurecerem'],
    explanation: 'No parque as crianças brincam; não congelam.',
    itemCorrect: 'Crianças',
  },
  {
    id: 'p3',
    textWithError: 'Maria colocou um pouco de perfume para iluminar o corpo.',
    wrongWord: 'iluminar',
    correctWord: 'perfumar',
    alternatives: ['perfumar', 'acender', 'clarear'],
    explanation: 'Perfumes servem para perfumar, não iluminar.',
    itemCorrect: 'Perfume',
  },
  {
    id: 'p4',
    textWithError: 'Para o lanche, Ana levou um caderno recheado de queijo.',
    wrongWord: 'caderno',
    correctWord: 'sanduíche',
    alternatives: ['sanduíche', 'livro', 'folha'],
    explanation: 'Come-se sanduíche, não caderno.',
    itemCorrect: 'Lanche',
  },
  {
    id: 'p5',
    textWithError: 'O pai pediu para o filho desligar a mesa antes de sair.',
    wrongWord: 'desligar',
    correctWord: 'arrumar',
    alternatives: ['arrumar', 'apertar', 'conectar'],
    explanation: 'Mesas não se desligam; arrumam-se.',
    itemCorrect: 'Mesa',
  },
  {
    id: 'p6',
    textWithError: 'A professora pediu que a turma afinasse o caderno.',
    wrongWord: 'afinasse',
    correctWord: 'organizasse',
    alternatives: ['organizasse', 'cantar', 'tocar'],
    explanation: 'Quem se afina é instrumento; cadernos se organizam.',
    itemCorrect: 'Caderno',
  },
  {
    id: 'p7',
    textWithError: 'Pedro abriu o guarda-chuva para escrever melhor na chuva.',
    wrongWord: 'escrever',
    correctWord: 'se proteger',
    alternatives: ['se proteger', 'anotar', 'copiar'],
    explanation: 'Guarda-chuva protege; não é usado para escrever.',
    itemCorrect: 'Guarda-chuva',
  },
  {
    id: 'p8',
    textWithError: 'O menino calçou as luvas para cheirar as mãos.',
    wrongWord: 'cheirar',
    correctWord: 'aquecer',
    alternatives: ['aquecer', 'soprar', 'perfumar'],
    explanation: 'Luvas servem para aquecer as mãos.',
    itemCorrect: 'Luvas',
  },
  {
    id: 'p9',
    textWithError: 'A mãe pediu para Clara temperar o quarto antes da visita chegar.',
    wrongWord: 'temperar',
    correctWord: 'arrumar',
    alternatives: ['arrumar', 'cozinhar', 'misturar'],
    explanation: 'Quartos não se temperam; arrumam-se.',
    itemCorrect: 'Quarto',
  },
  {
    id: 'p10',
    textWithError: 'Lucas colocou gelo na mochila para deixá-la mais confortável.',
    wrongWord: 'gelo',
    correctWord: 'almofada',
    alternatives: ['almofada', 'água', 'pedra'],
    explanation: 'Gelo não traz conforto; almofadas sim.',
    itemCorrect: 'Mochila',
  },
  {
    id: 'p11',
    textWithError: 'O cachorro deitou no caderno para descansar.',
    wrongWord: 'caderno',
    correctWord: 'cama',
    alternatives: ['cama', 'livro', 'lápis'],
    explanation: 'Cães descansam na cama ou no tapete, não em cadernos.',
    itemCorrect: 'Cão',
  },
  {
    id: 'p12',
    textWithError: 'A menina penteou o bolo antes da festa.',
    wrongWord: 'penteou',
    correctWord: 'decorou',
    alternatives: ['decorou', 'escovou', 'secou'],
    explanation: 'Penteia-se cabelo; bolo se decora.',
    itemCorrect: 'Bolo',
  },
  {
    id: 'p13',
    textWithError: 'Para assistir ao filme, Paulo colocou sal nos olhos.',
    wrongWord: 'sal',
    correctWord: 'óculos',
    alternatives: ['óculos', 'açúcar', 'água'],
    explanation: 'Usa-se óculos, não sal, para enxergar melhor.',
    itemCorrect: 'Filme',
  },
  {
    id: 'p14',
    textWithError: 'O garçom trouxe a chave quando pedimos a sobremesa.',
    wrongWord: 'chave',
    correctWord: 'sobremesa',
    alternatives: ['sobremesa', 'porta', 'cadeado'],
    explanation: 'Em restaurantes servem-se sobremesas, não chaves.',
    itemCorrect: 'Sobremesa',
  },
  {
    id: 'p15',
    textWithError: 'No outono, as árvores costumam roncar bastante.',
    wrongWord: 'roncar',
    correctWord: 'perder folhas',
    alternatives: ['perder folhas', 'dormir', 'gritar'],
    explanation: 'Árvores não roncam; perdem folhas.',
    itemCorrect: 'Árvores',
  },
  {
    id: 'p16',
    textWithError: 'A menina usou a esponja para desenhar no quadro.',
    wrongWord: 'esponja',
    correctWord: 'giz',
    alternatives: ['giz', 'espuma', 'sabão'],
    explanation: 'Desenha-se com giz no quadro.',
    itemCorrect: 'Quadro',
  },
  {
    id: 'p17',
    textWithError: 'Durante a tarde, os alunos mastigaram matemática.',
    wrongWord: 'mastigaram',
    correctWord: 'estudaram',
    alternatives: ['estudaram', 'comeram', 'picaram'],
    explanation: 'Mastiga-se comida; estuda-se matemática.',
    itemCorrect: 'Matemática',
  },
  {
    id: 'p18',
    textWithError: 'A avó pediu para ligarem a sopa.',
    wrongWord: 'ligarem',
    correctWord: 'esquentarem',
    alternatives: ['esquentarem', 'acender', 'conectar'],
    explanation: 'Sopa se esquenta; não se liga.',
    itemCorrect: 'Sopa',
  },
  {
    id: 'p19',
    textWithError: 'O atleta bebeu um guardanapo após a corrida.',
    wrongWord: 'guardanapo',
    correctWord: 'isotônico',
    alternatives: ['isotônico', 'toalha', 'papel'],
    explanation: 'Isotônicos se bebem; guardanapos não.',
    itemCorrect: 'Atleta',
  },
  {
    id: 'p20',
    textWithError: 'O garoto soprou o cachorro para que ele obedecesse.',
    wrongWord: 'soprou',
    correctWord: 'chamou',
    alternatives: ['chamou', 'empurrou', 'inflou'],
    explanation: 'Soprar não faz o cachorro obedecer; chamá-lo, sim.',
    itemCorrect: 'Cachorro',
  },
  {
    id: 'p21',
    textWithError: 'No café da manhã, Marina espalhou matemática no pão.',
    wrongWord: 'matemática',
    correctWord: 'manteiga',
    alternatives: ['manteiga', 'queijo', 'geleia'],
    explanation: 'Passa-se manteiga, não matemática, no pão.',
    itemCorrect: 'Pão',
  },
  {
    id: 'p22',
    textWithError: 'O aluno escreveu a redação usando uma panela azul.',
    wrongWord: 'panela',
    correctWord: 'caneta',
    alternatives: ['caneta', 'colher', 'prato'],
    explanation: 'Redações se escrevem com caneta.',
    itemCorrect: 'Redação',
  },
  {
    id: 'p23',
    textWithError: 'A garota secou a chuva com um sorriso.',
    wrongWord: 'secou',
    correctWord: 'enfrentou',
    alternatives: ['enfrentou', 'enxugou', 'apagou'],
    explanation: 'Não se seca a chuva; enfrenta-se.',
    itemCorrect: 'Chuva',
  },
  {
    id: 'p24',
    textWithError: 'O diretor comeu a ata da reunião ao final do encontro.',
    wrongWord: 'comeu',
    correctWord: 'assinou',
    alternatives: ['assinou', 'pintou', 'apagou'],
    explanation: 'Atas se assinam; não se comem.',
    itemCorrect: 'Ata',
  },
  {
    id: 'p25',
    textWithError: 'As crianças apagaram a bola para que ela ficasse mais leve.',
    wrongWord: 'apagaram',
    correctWord: 'esvaziaram',
    alternatives: ['esvaziaram', 'escreveram', 'pintaram'],
    explanation: 'Bolas se esvaziam para ficarem leves.',
    itemCorrect: 'Bola',
  },
  {
    id: 'p26',
    textWithError: 'Ela colocou molho na janela antes do almoço.',
    wrongWord: 'molho',
    correctWord: 'cortina',
    alternatives: ['cortina', 'salada', 'massa'],
    explanation: 'Janelas recebem cortinas, não molho.',
    itemCorrect: 'Janela',
  },
  {
    id: 'p27',
    textWithError: 'O menino bebeu o travesseiro para dormir melhor.',
    wrongWord: 'bebeu',
    correctWord: 'abraçou',
    alternatives: ['abraçou', 'mastigou', 'molhou'],
    explanation: 'Travesseiros se abraçam; não se bebem.',
    itemCorrect: 'Travesseiro',
  },
  {
    id: 'p28',
    textWithError: 'A professora carimbou a biblioteca para limpar o espaço.',
    wrongWord: 'carimbou',
    correctWord: 'organizou',
    alternatives: ['organizou', 'selou', 'furou'],
    explanation: 'Bibliotecas se organizam; não se carimbam.',
    itemCorrect: 'Biblioteca',
  },
  {
    id: 'p29',
    textWithError: 'O pai abriu o sapato para olhar o horário.',
    wrongWord: 'sapato',
    correctWord: 'relógio',
    alternatives: ['relógio', 'meia', 'cinto'],
    explanation: 'Consulta-se o horário no relógio.',
    itemCorrect: 'Relógio',
  },
  {
    id: 'p30',
    textWithError: 'A menina desligou o lápis ao terminar o exercício.',
    wrongWord: 'desligou',
    correctWord: 'guardou',
    alternatives: ['guardou', 'apertou', 'fechou'],
    explanation: 'Lápis se guarda; não se desliga.',
    itemCorrect: 'Lápis',
  },
  {
    id: 'p31',
    textWithError: 'O menino plantou o relógio no quintal para ver se crescia.',
    wrongWord: 'relógio',
    correctWord: 'semente',
    alternatives: ['semente', 'folha', 'flor'],
    explanation: 'Plantam-se sementes; relógios não crescem.',
    itemCorrect: 'Quintal',
  },
  {
    id: 'p32',
    textWithError: 'Ela penteou o chão antes de receber visitas.',
    wrongWord: 'penteou',
    correctWord: 'varreu',
    alternatives: ['varreu', 'escovou', 'secou'],
    explanation: 'Chão se varre; não se penteia.',
    itemCorrect: 'Chão',
  },
  {
    id: 'p33',
    textWithError: 'O estudante tomou um lápis para matar a sede.',
    wrongWord: 'lápis',
    correctWord: 'água',
    alternatives: ['água', 'tinta', 'papel'],
    explanation: 'Bebe-se água; não lápis.',
    itemCorrect: 'Estudante',
  },
  {
    id: 'p34',
    textWithError: 'No teatro, o ator vestiu alegria para cobrir o frio.',
    wrongWord: 'alegria',
    correctWord: 'casaco',
    alternatives: ['casaco', 'felicidade', 'sorriso'],
    explanation: 'Usa-se casaco contra o frio.',
    itemCorrect: 'Casaco',
  },
  {
    id: 'p35',
    textWithError: 'O bebê segurou o vento para não cair.',
    wrongWord: 'vento',
    correctWord: 'mão da mãe',
    alternatives: ['mão da mãe', 'ar', 'sopro'],
    explanation: 'Segura-se a mão de alguém; não o vento.',
    itemCorrect: 'Bebê',
  },
  {
    id: 'p36',
    textWithError: 'A cozinheira apagou o feijão para servir o jantar.',
    wrongWord: 'apagou',
    correctWord: 'temperou',
    alternatives: ['temperou', 'riscou', 'secou'],
    explanation: 'Feijão se tempera; não se apaga.',
    itemCorrect: 'Feijão',
  },
  {
    id: 'p37',
    textWithError: 'Ele amarrou o leite antes de colocar no copo.',
    wrongWord: 'amarrou',
    correctWord: 'despejou',
    alternatives: ['despejou', 'puxou', 'prendeu'],
    explanation: 'Leite se despeja; não se amarra.',
    itemCorrect: 'Leite',
  },
  {
    id: 'p38',
    textWithError: 'A menina esculpiu a lição de casa porque estava atrasada.',
    wrongWord: 'esculpiu',
    correctWord: 'fez',
    alternatives: ['fez', 'cortou', 'aparou'],
    explanation: 'Lições se fazem; não se esculpem.',
    itemCorrect: 'Lição',
  },
  {
    id: 'p39',
    textWithError: 'O garoto usou cola para afinar o cabelo.',
    wrongWord: 'afinar',
    correctWord: 'arrumar',
    alternatives: ['arrumar', 'pintar', 'cortar'],
    explanation: 'Cabelos se arrumam; não se afinam com cola.',
    itemCorrect: 'Cabelo',
  },
  {
    id: 'p40',
    textWithError: 'Para descansar, a família estacionou o sofá na garagem.',
    wrongWord: 'estacionou',
    correctWord: 'colocou',
    alternatives: ['colocou', 'dirigiu', 'manobrou'],
    explanation: 'Sofás se colocam; carros se estacionam.',
    itemCorrect: 'Sofá',
  },
  {
    id: 'p41',
    textWithError: 'A menina passou perfume na televisão antes da visita.',
    wrongWord: 'perfume',
    correctWord: 'pano',
    alternatives: ['pano', 'creme', 'tinta'],
    explanation: 'Limpa-se TV com pano; não com perfume.',
    itemCorrect: 'Televisão',
  },
  {
    id: 'p42',
    textWithError: 'Ele girou o lápis para abrir a porta.',
    wrongWord: 'lápis',
    correctWord: 'chave',
    alternatives: ['chave', 'borracha', 'caderno'],
    explanation: 'Portas se abrem com chaves.',
    itemCorrect: 'Porta',
  },
  {
    id: 'p43',
    textWithError: 'O aluno congelou a prova depois de terminar.',
    wrongWord: 'congelou',
    correctWord: 'entregou',
    alternatives: ['entregou', 'escondeu', 'dobrou'],
    explanation: 'Provas se entregam; não se congelam.',
    itemCorrect: 'Prova',
  },
];
